parameters:
    debug:         true
    user_provider: debug
    user_provider_ntlm_domain: ~
    notification_email_sender: ~
    db_driver:     pdo_mysql
    db_host:       localhost
    db_port:       ~
    db_dbname:     talkly
    db_user:       talkly
    db_password:
    db_charset:    UTF8
