parameters:
    debug:         true
    user_provider: debug
    user_provider_ntlm_domain: ~
    notification_email_sender: ~
    database_driver:     pdo_mysql
    database_host:       localhost
    database_port:       ~
    database_name:       talkly
    database_user:       talkly
    database_password:
    database_charset:    UTF8
    secret:              secure
    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~
